# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FanucParameterCompareQTgui_221101.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 202)
        self.Msg4textBrowser = QtWidgets.QTextBrowser(MainWindow)
        self.Msg4textBrowser.setGeometry(QtCore.QRect(10, 80, 381, 101))
        self.Msg4textBrowser.setObjectName("Msg4textBrowser")
        self.layoutWidget = QtWidgets.QWidget(MainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 13, 551, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.File1lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.File1lineEdit.setObjectName("File1lineEdit")
        self.horizontalLayout.addWidget(self.File1lineEdit)
        self.File1pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.File1pushButton.setObjectName("File1pushButton")
        self.horizontalLayout.addWidget(self.File1pushButton)
        self.file1CSVpushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.file1CSVpushButton.setObjectName("file1CSVpushButton")
        self.horizontalLayout.addWidget(self.file1CSVpushButton)
        self.layoutWidget1 = QtWidgets.QWidget(MainWindow)
        self.layoutWidget1.setGeometry(QtCore.QRect(13, 44, 551, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.File2lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.File2lineEdit.setObjectName("File2lineEdit")
        self.horizontalLayout_2.addWidget(self.File2lineEdit)
        self.File2pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.File2pushButton.setObjectName("File2pushButton")
        self.horizontalLayout_2.addWidget(self.File2pushButton)
        self.file2CSVpushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.file2CSVpushButton.setObjectName("file2CSVpushButton")
        self.horizontalLayout_2.addWidget(self.file2CSVpushButton)
        self.layoutWidget2 = QtWidgets.QWidget(MainWindow)
        self.layoutWidget2.setGeometry(QtCore.QRect(400, 80, 161, 101))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GoCpmarepushButton = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GoCpmarepushButton.setFont(font)
        self.GoCpmarepushButton.setObjectName("GoCpmarepushButton")
        self.verticalLayout.addWidget(self.GoCpmarepushButton)
        self.OpenResultpushButton = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.OpenResultpushButton.setFont(font)
        self.OpenResultpushButton.setObjectName("OpenResultpushButton")
        self.verticalLayout.addWidget(self.OpenResultpushButton)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FanucParameterCompareQTgui_byJIR_221101"))
        self.File1pushButton.setText(_translate("MainWindow", "open FILE 1"))
        self.file1CSVpushButton.setText(_translate("MainWindow", "file1 txt2CSV"))
        self.File2pushButton.setText(_translate("MainWindow", "open FILE 2"))
        self.file2CSVpushButton.setText(_translate("MainWindow", "file2 txt2CSV"))
        self.GoCpmarepushButton.setText(_translate("MainWindow", "Go Compare"))
        self.OpenResultpushButton.setText(_translate("MainWindow", "Open Result"))
